apiVersion: jenkins.krateo.io/v1alpha1
kind: ProviderConfig
metadata:
  name: jenkins-providerconfig
spec:
  baseUrl: https://jenkins.pipem.io
  #controller: ocp-master-01
  username: Admin
  verbose: true
  insecure: true
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: jenkins-secret
      key: apiToken